-- Add developerId to Repo and create per-developer tech stack + detector rule tables

-- Add developerId to Repo (optional to avoid breaking existing rows)
ALTER TABLE "Repo"
ADD COLUMN "developerId" INTEGER;

-- Link repos to developers
ALTER TABLE "Repo"
ADD CONSTRAINT "Repo_developerId_fkey"
FOREIGN KEY ("developerId") REFERENCES developers ("id")
ON DELETE SET NULL ON UPDATE CASCADE;

-- Per-developer tech stack scores
CREATE TABLE "developer_tech_stacks" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "developerId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "percentage" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now(),

    CONSTRAINT "developer_tech_stacks_developerId_fkey"
        FOREIGN KEY ("developerId") REFERENCES developers ("id")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "developer_tech_stacks_developerId_name_key" UNIQUE ("developerId", "name")
);

-- Framework/tool detector rules stored in DB
CREATE TABLE "tech_detector_rules" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "file" TEXT NOT NULL,
    "keyword" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now()
);

