-- Architecture detection tables (global + per-developer)

-- Global architecture counts
CREATE TABLE "architectures" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "count" INTEGER NOT NULL,

    CONSTRAINT "architectures_name_key" UNIQUE ("name")
);

-- Per-developer architecture counts
CREATE TABLE "developer_architectures" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "developerId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "count" INTEGER NOT NULL,

    CONSTRAINT "developer_architectures_developerId_fkey"
        FOREIGN KEY ("developerId") REFERENCES developers ("id")
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT "developer_architectures_name_fkey"
        FOREIGN KEY ("name") REFERENCES architectures ("name")
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT "developer_architectures_unique" UNIQUE ("developerId", "name")
);

